spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  mvc:
    contentnegotiation:
      favor-parameter: true

server:
  port: 8081
  error:
    include-message: always
    include-exception: true
  servlet:
    context-path: /spring-boot-rest
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
